### ISSUE TITLE
Signup with e-mail and password, no FB account required

### ISSUE THREAD

**Issue by alexgleason** [tanel/meet-a-vegan.com#4]
Hi, interesting project. I noticed the "log in with Facebook" button reaches a 404 on the demo site. I'm guessing it's a work in progress?

Also just chiming in that I don't have a Facebook account, so I wouldn't be able to access it.

**Comment by tanel** [comment]
Hi! The log in with Facebook is done but is not deployed yet (I need to set up database on the server so it will take couple of days approx).

I was thinking of primarily allowing people to log in/sign up using Facebook, so that we get their profile picture easily. But surely we could add signup with just an e-mail, too.

BTW Do you have any ideas about what you'd like to see in the app? At the moment I'm thinking about "vegan social", an app that allows you to meet (other) vegans so it's a bit like Tinder but not only for dating + Facebook events

**Comment by alexgleason** [comment]
I'm probably not the target audience, but I'm appreciative of any social platform that's open source and respects my privacy. I'm not looking to date right now either, but I'd be interested in connecting with more local vegans.

I'd advocate it to my vegan friends who use Tinder.

**Comment by ElonSatoshi** [comment]
Facebook is nonfree. Could you let people sign up with free software social media, such as Diaspora, Mastodon, or Friendica?

**Comment by tanel** [comment]
@ElonSatoshi the FB signup/login is done using OAuth2 - should these free social media sites have OAuth then it should be easy to integrate with those. 

If they don't then e-mail and password should cover these use cases.

PS. Thanks a lot for the input!
